name: "terraform-deploy"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: eu-central-1
       

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Setup Terraform
        #uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
            rm -rf .terraform
            terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
