name: Terraform AWS Workflow Destroy

on:
  workflow_dispatch:

jobs:
  tf_code_check:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform init, plan and apply
      run: |
        echo "** Running Terraform Init**"
        terraform init
        
        echo "** Running Terraform Validate**"
        terraform validate
        
        echo "** Running Terraform Plan**"
        terraform plan -destroy
        
        echo "** Running Terraform Apply**"
        terraform destroy -auto-approve
